FROM node:22-alpine
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/types/ ./packages/types/
COPY apps/frontend/ ./apps/frontend/

RUN pnpm install

WORKDIR /app/apps/frontend
EXPOSE 5174
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "5174"]